# Generated by Django 4.2.3 on 2023-07-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_delete_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('comision', models.IntegerField()),
                ('nombreAlumno', models.CharField(max_length=50)),
            ],
        ),
    ]
