# Generated by Django 4.2.3 on 2023-07-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='descuentoEspecial',
            field=models.CharField(max_length=50),
        ),
    ]
